# Generated by Django 4.1.3 on 2022-11-21 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trellouser",
            name="preferred",
            field=models.JSONField(default={}),
        ),
    ]
