# Generated by Django 4.1.3 on 2022-11-21 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_trellouser_favourite"),
    ]

    operations = [
        migrations.AddField(
            model_name="trellouser",
            name="favourite",
            field=models.JSONField(default={}),
        ),
    ]
