# Generated by Django 4.1.3 on 2022-11-21 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="board",
            name="image",
            field=models.ImageField(blank=True, upload_to="Backgrounds"),
        ),
    ]
