# Generated by Django 4.1.3 on 2022-11-22 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_alter_board_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="board",
            name="members",
            field=models.JSONField(default={}, null=True),
        ),
    ]
