# Generated by Django 4.1.3 on 2022-11-22 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_mark_checklist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mark",
            name="colour",
            field=models.CharField(default=None, max_length=15, null=True),
        ),
    ]
